version: '2.0'

services:
  config:
    build:
      context: .
      dockerfile: prod_config.dockerfile
    volumes:
      - /etc/nginx
  code:
    build:
      context: .
      dockerfile: code.dockerfile
    volumes:
      - /var/www/app
  nginx:
    image: nginx:alpine
    depends_on:
      - php
    volumes_from:
      - config
      - code
    ports:
      - "8080:80"
    links:
      - php
  php:
    image: php:fpm-alpine
    volumes_from:
      - code
    ports:
      - "9000"
